#!/usr/bin/env python3
"""Clean and update literature.bib.

Pipeline:
  1. (opt-in) Remove unreferenced entries.
  2. DBLP key/biburl refresh — for entries that already have a DBLP key.
  3. arXiv-aware lookup — detect arXiv id; query DBLP for all records of
     that work; promote to a non-CoRR record (conf/journal/workshop) when
     available; rename the citation key to the new DBLP key.
  4. Crossref fallback — if DBLP has only the CoRR record, search Crossref
     by title for a published DOI; retry DBLP by DOI; else take Crossref.
  5. Strip arXiv metadata from already-published entries (entries with a
     booktitle or non-CoRR journal that still carry eprint/archiveprefix/
     primaryclass/eprinttype, and a redundant arXiv url alongside a
     non-arXiv DOI).
  6. Rewrite \\cite sites in all .tex files for any renamed keys.
  7. Write updated bib + cache + report.

A persistent JSON cache at scripts/.bib_validation_cache.json records the
last validation timestamp, content hash, and outcome per entry; subsequent
runs skip cached entries that are fresh (< --max-age-days) and unchanged
unless --force is passed.
"""

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import time
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote

import bibtexparser
from bibtexparser.bparser import BibTexParser
from bibtexparser.bwriter import BibTexWriter

PROJECT = Path(__file__).resolve().parent.parent
BIB_FILE = PROJECT / "literature.bib"
AUX_FILE = PROJECT / "emse25-llm-guidelines.aux"
BACKUP_FILE = PROJECT / "literature.bib.backup"
REPORT_FILE = PROJECT / "dblp_unmatched_report.txt"
CACHE_FILE = PROJECT / "scripts" / ".bib_validation_cache.json"

DBLP_REC_URL = "https://dblp.uni-trier.de/rec/{key}.bib"
DBLP_SEARCH_URL = "https://dblp.uni-trier.de/search/publ/api?q={query}&format=json&h=10"
CROSSREF_WORKS = "https://api.crossref.org/works"
DBLP_RATE_LIMIT_S = 2

CITE_RE = re.compile(r"\\cite[a-z]*\*?\s*(?:\[[^\]]*\]\s*){0,2}\{([^}]+)\}")
CITE_REWRITE_RE = re.compile(
    r"(\\cite[a-z]*\*?\s*(?:\[[^\]]*\]\s*){0,2}\{)([^}]+)(\})"
)
AUX_CITE_RE = re.compile(r"\\citation\{([^}]+)\}")
COMMENT_RE = re.compile(r"(?<!\\)%.*$", re.MULTILINE)

ARXIV_FIELDS_TO_STRIP = ("eprint", "archiveprefix", "primaryclass", "eprinttype")
TEX_DIRS = ("_guidelines", "_studytypes", "_scope", "_main", "_summary", "_tldr",
            "reviews-and-response")
TEX_EXCLUDE = ("emse25-llm-guidelines-flat.tex",)  # generated by flatten.sh


# ── Network helpers ─────────────────────────────────────────────────────────

def fetch_url(url, timeout=15, retries=3):
    """Fetch URL via curl, retrying on 429/transient failures."""
    for attempt in range(retries):
        try:
            result = subprocess.run(
                ["curl", "-sSL", "-w", "\n%{http_code}",
                 "--max-time", str(timeout),
                 "--user-agent", "literature.bib cleaner (mailto:seba@sbaltes.com)",
                 url],
                capture_output=True, text=True, timeout=timeout + 5,
            )
            if result.returncode == 0 and result.stdout.strip():
                lines = result.stdout.rsplit("\n", 1)
                body = lines[0] if len(lines) > 1 else result.stdout
                status = lines[-1].strip() if len(lines) > 1 else ""
                if status == "429":
                    wait = 3 * (attempt + 1)
                    print(f"(429, wait {wait}s) ", end="", flush=True)
                    time.sleep(wait)
                    continue
                if status.startswith("2") and body.strip():
                    return body
        except (subprocess.TimeoutExpired, OSError):
            pass
        if attempt < retries - 1:
            time.sleep(2)
    return None


def parse_single_bib(bib_str):
    """Parse a bib string and return the first entry dict, or None."""
    parser = BibTexParser(common_strings=True)
    parser.ignore_nonstandard_types = False
    try:
        db = bibtexparser.loads(bib_str, parser=parser)
        if db.entries:
            return db.entries[0]
    except Exception:
        pass
    return None


# ── Title / arxiv-id helpers ────────────────────────────────────────────────

def normalize_title(title):
    """Normalize a title for comparison."""
    t = title.lower()
    t = re.sub(r"[{}\\]", "", t)
    t = unicodedata.normalize("NFKD", t)
    t = re.sub(r"[^a-z0-9 ]", "", t)
    t = re.sub(r"\s+", " ", t).strip()
    return t


ARXIV_NEW = re.compile(r"(\d{4}\.\d{4,5})(?:v\d+)?")
ARXIV_OLD = re.compile(r"([a-z\-]+/\d{7})(?:v\d+)?")


def arxiv_id_from_entry(entry):
    """Extract a normalized arXiv id (e.g., '2107.03374' or 'cs/0501001').

    Looks at eprint, ID (DBLP CoRR key), url, doi (10.48550/arXiv.*), and
    volume ('abs/...') fields.
    """
    # Direct eprint
    eprint = entry.get("eprint", "").strip()
    m = ARXIV_NEW.fullmatch(eprint) or ARXIV_OLD.fullmatch(eprint)
    if m:
        return m.group(1)

    # DBLP CoRR key
    key = entry.get("ID", "")
    m = re.match(r"^DBLP:journals/corr/abs-(\d{4})-(\d{4,5})$", key)
    if m:
        return f"{m.group(1)}.{m.group(2)}"

    # url
    url = entry.get("url", "")
    m = re.search(r"arxiv\.org/abs/(\d{4}\.\d{4,5})", url, re.I)
    if m:
        return m.group(1)
    m = re.search(r"arxiv\.org/abs/([a-z\-]+/\d{7})", url, re.I)
    if m:
        return m.group(1)

    # volume "abs/2306.13298"
    vol = entry.get("volume", "")
    m = re.match(r"^abs/(\d{4}\.\d{4,5})$", vol)
    if m:
        return m.group(1)

    # arXiv DOI
    doi = entry.get("doi", "").lower()
    m = re.search(r"10\.48550/arxiv\.(\d{4}\.\d{4,5})", doi)
    if m:
        return m.group(1)
    return None


def is_arxiv_or_corr(entry):
    """Entry's primary venue is arXiv/CoRR (no other venue named).

    An entry with a real booktitle or non-CoRR journal is *not* arxiv-only,
    even if it carries leftover arXiv metadata fields.
    """
    if entry.get("booktitle", "").strip():
        return False
    journal = entry.get("journal", "").lower().strip()
    if journal and journal not in ("corr", "arxiv"):
        return False
    if journal in ("corr", "arxiv"):
        return True
    if "arxiv" in entry.get("archiveprefix", "").lower():
        return True
    if entry.get("ID", "").startswith("DBLP:journals/corr/"):
        return True
    return False


def is_misc_with_url(entry):
    return (entry.get("ENTRYTYPE", "").lower() == "misc"
            and "howpublished" in entry
            and "\\url{" in entry.get("howpublished", ""))


# ── DBLP helpers ────────────────────────────────────────────────────────────

def fetch_dblp_by_key(dblp_rec_key):
    """Fetch a DBLP entry by record key (e.g., 'conf/icse/Foo24')."""
    url = DBLP_REC_URL.format(key=dblp_rec_key)
    bib_str = fetch_url(url)
    if bib_str:
        return parse_single_bib(bib_str)
    return None


def dblp_records_for_title(title):
    """Search DBLP by title; return list of (rec_key, info_dict) for records
    whose title normalizes to the same string."""
    url = DBLP_SEARCH_URL.format(query=quote(title))
    raw = fetch_url(url)
    if not raw:
        return []
    try:
        data = json.loads(raw)
        hits = data.get("result", {}).get("hits", {}).get("hit", [])
    except (json.JSONDecodeError, KeyError):
        return []
    norm_local = normalize_title(title)
    matches = []
    for hit in hits:
        info = hit.get("info", {})
        dblp_title = info.get("title", "")
        if dblp_title.endswith("."):
            dblp_title = dblp_title[:-1]
        if normalize_title(dblp_title) == norm_local:
            matches.append((info.get("key", ""), info))
    return matches


def dblp_records_for_doi(doi):
    """Search DBLP by DOI; return list of (rec_key, info_dict)."""
    if not doi:
        return []
    url = DBLP_SEARCH_URL.format(query=quote(doi))
    raw = fetch_url(url)
    if not raw:
        return []
    try:
        data = json.loads(raw)
        hits = data.get("result", {}).get("hits", {}).get("hit", [])
    except (json.JSONDecodeError, KeyError):
        return []
    matches = []
    needle = doi.lower()
    for hit in hits:
        info = hit.get("info", {})
        if info.get("doi", "").lower() == needle:
            matches.append((info.get("key", ""), info))
    return matches


def pick_best_dblp_record(records):
    """Prefer non-CoRR records over CoRR. If multiple non-CoRR, prefer the
    most recent year, then the longest key (heuristic: more specific)."""
    if not records:
        return None
    non_corr = [r for r in records if not r[0].startswith("journals/corr/")]
    if non_corr:
        def sort_key(r):
            year = r[1].get("year", "0")
            try:
                y = int(year)
            except ValueError:
                y = 0
            return (-y, -len(r[0]))
        non_corr.sort(key=sort_key)
        return non_corr[0]
    return records[0]


def has_dblp_biburl(entry):
    return "dblp.org" in entry.get("biburl", "")


def dblp_key_from_biburl(entry):
    biburl = entry.get("biburl", "")
    m = re.search(r"dblp\.org/rec/(.+?)\.bib", biburl)
    return m.group(1) if m else None


# ── Crossref helpers ────────────────────────────────────────────────────────

def crossref_search_by_title(title):
    """Search Crossref by title; return the message dict for the best
    non-arXiv match, or None."""
    url = f"{CROSSREF_WORKS}?query.title={quote(title)}&rows=5"
    raw = fetch_url(url, timeout=20)
    if not raw:
        return None
    try:
        data = json.loads(raw)
        items = data.get("message", {}).get("items", [])
    except (json.JSONDecodeError, KeyError):
        return None
    norm_local = normalize_title(title)
    for item in items:
        for ct in item.get("title", []):
            if normalize_title(ct) == norm_local:
                doi = item.get("DOI", "")
                if "10.48550/arxiv" in doi.lower():
                    continue
                return item
    return None


def crossref_to_entry(item, citation_key):
    """Convert a Crossref item into a bib entry dict."""
    type_map = {
        "journal-article": "article",
        "proceedings-article": "inproceedings",
        "book-chapter": "incollection",
        "book": "book",
        "monograph": "book",
        "report": "techreport",
    }
    cr_type = item.get("type", "")
    bib_type = type_map.get(cr_type, "misc")

    entry = {"ENTRYTYPE": bib_type, "ID": citation_key}

    authors = item.get("author", [])
    if authors:
        names = []
        for a in authors:
            given = a.get("given", "").strip()
            family = a.get("family", "").strip()
            if family and given:
                names.append(f"{family}, {given}")
            elif family:
                names.append(family)
        if names:
            entry["author"] = " and ".join(names)

    titles = item.get("title", [])
    if titles:
        entry["title"] = titles[0]

    container = item.get("container-title", [])
    if container:
        if bib_type == "inproceedings":
            entry["booktitle"] = container[0]
        else:
            entry["journal"] = container[0]

    if item.get("volume"):
        entry["volume"] = item["volume"]
    if item.get("issue"):
        entry["number"] = item["issue"]
    if item.get("page"):
        entry["pages"] = item["page"]
    if item.get("publisher"):
        entry["publisher"] = item["publisher"]
    issns = item.get("ISSN")
    if issns:
        entry["issn"] = issns[0]
    if item.get("DOI"):
        entry["doi"] = item["DOI"]
    pub = item.get("published") or item.get("issued") or {}
    parts = pub.get("date-parts", [[]])
    if parts and parts[0]:
        entry["year"] = str(parts[0][0])
    return entry


# ── Strip arxiv meta from published entries ─────────────────────────────────

def is_published_with_arxiv_meta(entry):
    """Entry has a venue but still carries arxiv-only metadata."""
    etype = entry.get("ENTRYTYPE", "").lower()
    journal = entry.get("journal", "").lower()
    has_venue = bool(entry.get("booktitle")) or (
        etype == "article" and journal and journal not in ("corr", "arxiv")
    )
    if not has_venue:
        return False
    if any(entry.get(f) for f in ARXIV_FIELDS_TO_STRIP):
        return True
    url = entry.get("url", "")
    doi = entry.get("doi", "")
    if "arxiv.org" in url.lower() and doi and "10.48550/arxiv" not in doi.lower():
        return True
    return False


def strip_arxiv_meta(entry):
    """Remove arxiv-only fields. Returns sorted list of stripped field names."""
    stripped = []
    for f in ARXIV_FIELDS_TO_STRIP:
        if f in entry:
            del entry[f]
            stripped.append(f)
    url = entry.get("url", "")
    doi = entry.get("doi", "")
    if "arxiv.org" in url.lower() and doi and "10.48550/arxiv" not in doi.lower():
        del entry["url"]
        stripped.append("url")
    vol = entry.get("volume", "")
    if vol.startswith("abs/") and entry.get("journal", "").lower() not in ("corr", "arxiv"):
        del entry["volume"]
        stripped.append("volume")
    return sorted(stripped)


# ── Cache ───────────────────────────────────────────────────────────────────

def entry_hash(entry):
    """Stable hash of entry content (excluding ID/ENTRYTYPE) for change detection."""
    items = sorted((k, v) for k, v in entry.items() if k not in ("ID", "ENTRYTYPE"))
    h = hashlib.sha256()
    for k, v in items:
        h.update(k.encode())
        h.update(b"=")
        h.update(v.encode())
        h.update(b"\n")
    return h.hexdigest()[:16]


def load_cache():
    if CACHE_FILE.exists():
        try:
            return json.loads(CACHE_FILE.read_text())
        except Exception:
            return {}
    return {}


def save_cache(cache):
    CACHE_FILE.parent.mkdir(parents=True, exist_ok=True)
    CACHE_FILE.write_text(json.dumps(cache, indent=2, sort_keys=True))


def is_fresh(cache_rec, content_hash, max_age_days):
    if not cache_rec:
        return False
    if cache_rec.get("content_hash") != content_hash:
        return False
    last = cache_rec.get("last_checked")
    if not last:
        return False
    try:
        last_dt = datetime.fromisoformat(last)
    except ValueError:
        return False
    if last_dt.tzinfo is None:
        last_dt = last_dt.replace(tzinfo=timezone.utc)
    age = datetime.now(timezone.utc) - last_dt
    return age.days < max_age_days


def now_iso():
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


# ── Step 1: remove unreferenced ─────────────────────────────────────────────

def keys_from_tex_files():
    keys = set()
    for tex in PROJECT.rglob("*.tex"):
        text = tex.read_text(errors="replace")
        text = COMMENT_RE.sub("", text)
        for m in CITE_RE.finditer(text):
            for k in m.group(1).split(","):
                k = k.strip()
                if k:
                    keys.add(k)
    return keys


def keys_from_aux():
    keys = set()
    if not AUX_FILE.exists():
        return keys
    text = AUX_FILE.read_text(errors="replace")
    for m in AUX_CITE_RE.finditer(text):
        for k in m.group(1).split(","):
            k = k.strip()
            if k:
                keys.add(k)
    return keys


def remove_unreferenced(bib_db, referenced):
    kept, removed = [], []
    for entry in bib_db.entries:
        if entry["ID"] in referenced:
            kept.append(entry)
        else:
            removed.append(entry["ID"])
    bib_db.entries = kept
    return removed


# ── Step 2/3/4: validate one entry against DBLP / Crossref ──────────────────

def lookup_better_record(entry):
    """Try to find a better DBLP/Crossref record for entry.

    Returns (new_entry_or_None, new_key_or_None, source_label, reason).
    new_entry is a parsed dict; new_key is the DBLP record key (e.g.,
    'conf/icse/Foo24') or None when no rename is needed.
    """
    title = entry.get("title", "").strip()
    arxiv_id = arxiv_id_from_entry(entry)

    candidates = []  # list of (rec_key, parsed_entry)

    # 1. Existing DBLP key/biburl
    rec_key = None
    if entry["ID"].startswith("DBLP:"):
        rec_key = entry["ID"][5:]
    elif has_dblp_biburl(entry):
        rec_key = dblp_key_from_biburl(entry)
    if rec_key:
        e = fetch_dblp_by_key(rec_key)
        if e:
            candidates.append((rec_key, e))
        time.sleep(DBLP_RATE_LIMIT_S)

    # 2. arXiv-aware: search DBLP by title to find the published version too
    if arxiv_id and title:
        for k, _info in dblp_records_for_title(title):
            if k and not any(k == c[0] for c in candidates):
                e = fetch_dblp_by_key(k)
                if e:
                    candidates.append((k, e))
                time.sleep(DBLP_RATE_LIMIT_S)
        time.sleep(DBLP_RATE_LIMIT_S)
    elif title and not candidates:
        # Plain title search for entries with no DBLP key
        for k, _info in dblp_records_for_title(title):
            if k:
                e = fetch_dblp_by_key(k)
                if e:
                    candidates.append((k, e))
                time.sleep(DBLP_RATE_LIMIT_S)

    if candidates:
        best_rec_key, best_entry = pick_best_dblp_record(candidates)
        return best_entry, best_rec_key, "dblp", ""

    # 3. Crossref fallback (only if entry looks like an arxiv preprint)
    if title and is_arxiv_or_corr(entry):
        item = crossref_search_by_title(title)
        if item:
            doi = item.get("DOI", "")
            if doi:
                # Re-query DBLP by DOI
                for k, _info in dblp_records_for_doi(doi):
                    if k:
                        e = fetch_dblp_by_key(k)
                        if e:
                            return e, k, "dblp-via-crossref", ""
                        time.sleep(DBLP_RATE_LIMIT_S)
            cr_entry = crossref_to_entry(item, entry["ID"])
            return cr_entry, None, "crossref", ""

    return None, None, "", "no DBLP/Crossref match"


# ── Step 5: rewrite cite sites in .tex ──────────────────────────────────────

def collect_tex_files():
    files = []
    for sub in TEX_DIRS:
        d = PROJECT / sub
        if d.is_dir():
            files.extend(d.rglob("*.tex"))
    for f in PROJECT.glob("*.tex"):
        if f.name not in TEX_EXCLUDE:
            files.append(f)
    return sorted(set(files))


def rewrite_tex_citations(rename_map, dry_run=False):
    """Rewrite \\cite[t|p|author]?\\*?{...} sites for renamed keys.

    Preserves the original separator whitespace between keys (e.g., ", ").
    Returns dict of relative-path -> count of replaced occurrences.
    """
    if not rename_map:
        return {}
    counts = {}
    for tex in collect_tex_files():
        original = tex.read_text(errors="replace")
        replacements = [0]

        def repl(m):
            parts = m.group(2).split(",")
            new_parts = []
            changed = False
            for part in parts:
                stripped = part.strip()
                new_key = rename_map.get(stripped, stripped)
                if new_key != stripped:
                    leading_len = len(part) - len(part.lstrip())
                    trailing_len = len(part) - len(part.rstrip())
                    leading = part[:leading_len]
                    trailing = part[len(part) - trailing_len:] if trailing_len else ""
                    new_parts.append(f"{leading}{new_key}{trailing}")
                    changed = True
                    replacements[0] += 1
                else:
                    new_parts.append(part)
            if not changed:
                return m.group(0)
            return m.group(1) + ",".join(new_parts) + m.group(3)

        new_text = CITE_REWRITE_RE.sub(repl, original)
        if replacements[0]:
            counts[str(tex.relative_to(PROJECT))] = replacements[0]
            if not dry_run:
                tex.write_text(new_text)
    return counts


# ── Main pipeline ───────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--force", action="store_true",
                   help="Ignore cache; re-validate every entry.")
    p.add_argument("--only", default="",
                   help="Comma-separated list of citation keys to process exclusively.")
    p.add_argument("--max-age-days", type=int, default=30,
                   help="Re-validate cached entries older than N days (default 30).")
    p.add_argument("--remove-unref", action="store_true",
                   help="Run Step 1 (remove unreferenced entries). Default off.")
    p.add_argument("--no-rename", action="store_true",
                   help="Don't rename citation keys to DBLP keys.")
    p.add_argument("--no-tex-update", action="store_true",
                   help="Don't rewrite cite sites in .tex files (still rename in bib).")
    p.add_argument("--no-strip", action="store_true",
                   help="Don't strip arXiv metadata from already-published entries.")
    p.add_argument("--dry-run", action="store_true",
                   help="Print actions; don't write any files.")
    p.add_argument("--limit", type=int, default=0,
                   help="Process at most N entries (0 = no limit). Useful for testing.")
    return p.parse_args()


def select_entries(bib_db, only_keys):
    """Yield (idx, entry) for entries to consider, applying --only filter."""
    for i, e in enumerate(bib_db.entries):
        if only_keys and e["ID"] not in only_keys:
            continue
        yield i, e


def process_entry(entry, args):
    """Run lookup + decide outcome. Returns dict:
        {outcome, new_entry, new_key, stripped_fields, reason}
    Possible outcomes:
        upgraded      — replaced with non-CoRR DBLP record (rename candidate)
        normalized    — refreshed with DBLP record (same venue category)
        stripped      — only stripped arxiv metadata
        no_change     — nothing to do
        no_match      — no DBLP/Crossref result
        skip_misc     — @misc with howpublished URL
    """
    if is_misc_with_url(entry):
        return {"outcome": "skip_misc", "new_entry": None, "new_key": None,
                "stripped_fields": [], "reason": "@misc with howpublished URL"}

    new_entry, new_rec_key, source, reason = lookup_better_record(entry)

    if new_entry is None:
        # No DBLP match. Optionally still strip arxiv meta from published-looking
        # entries that have a manually-curated venue (rare).
        if not args.no_strip and is_published_with_arxiv_meta(entry):
            stripped = strip_arxiv_meta(entry)
            return {"outcome": "stripped", "new_entry": None, "new_key": None,
                    "stripped_fields": stripped, "reason": "kept entry; stripped arxiv meta"}
        return {"outcome": "no_match", "new_entry": None, "new_key": None,
                "stripped_fields": [], "reason": reason}

    # Guard: never downgrade a published local entry to a CoRR DBLP record.
    # If DBLP only has the preprint but the local entry already names a venue,
    # keep local and only strip arxiv meta.
    if is_arxiv_or_corr(new_entry) and not is_arxiv_or_corr(entry):
        if not args.no_strip and is_published_with_arxiv_meta(entry):
            stripped = strip_arxiv_meta(entry)
            return {"outcome": "stripped", "new_entry": None, "new_key": None,
                    "stripped_fields": stripped,
                    "reason": "DBLP only has CoRR; kept local venue, stripped arxiv meta"}
        return {"outcome": "no_change", "new_entry": None, "new_key": None,
                "stripped_fields": [],
                "reason": "DBLP only has CoRR; local already has venue"}

    # Compute the candidate citation key. We rename to a DBLP key whenever
    # one is available (uniformity across the bib), unless --no-rename is set.
    upgraded = is_arxiv_or_corr(entry) and not is_arxiv_or_corr(new_entry)
    candidate_id = entry["ID"]
    if not args.no_rename and new_rec_key:
        candidate_id = f"DBLP:{new_rec_key}"
    new_entry["ID"] = candidate_id

    # Strip arxiv meta from the new entry if it now has a venue
    if not args.no_strip and is_published_with_arxiv_meta(new_entry):
        strip_arxiv_meta(new_entry)

    if upgraded:
        return {"outcome": "upgraded", "new_entry": new_entry,
                "new_key": candidate_id if candidate_id != entry["ID"] else None,
                "stripped_fields": [], "reason": f"via {source}"}

    # Same category — replace if DBLP record adds metadata or rename is needed.
    metadata_fields = {"doi", "pages", "volume", "number", "publisher", "booktitle"}
    local_count = sum(1 for f in metadata_fields if entry.get(f))
    new_count = sum(1 for f in metadata_fields if new_entry.get(f))
    key_changes = candidate_id != entry["ID"]
    if new_count > local_count or key_changes:
        return {"outcome": "normalized", "new_entry": new_entry,
                "new_key": candidate_id if key_changes else None,
                "stripped_fields": [], "reason": f"via {source}"}

    # No improvement; check if we should at least strip arxiv meta from current
    if not args.no_strip and is_published_with_arxiv_meta(entry):
        stripped = strip_arxiv_meta(entry)
        return {"outcome": "stripped", "new_entry": None, "new_key": None,
                "stripped_fields": stripped, "reason": "DBLP not better; stripped arxiv meta"}

    return {"outcome": "no_change", "new_entry": None, "new_key": None,
            "stripped_fields": [], "reason": ""}


def write_report(removed, results, rename_map, tex_counts):
    lines = []
    lines.append("=" * 72)
    lines.append(f"Bibliography Cleanup Report  ({now_iso()})")
    lines.append("=" * 72)
    lines.append("")
    counts = {}
    for r in results.values():
        counts[r["outcome"]] = counts.get(r["outcome"], 0) + 1
    if removed:
        lines.append(f"Unreferenced entries removed:    {len(removed)}")
    for label in ("upgraded", "normalized", "stripped",
                  "no_change", "no_match", "skip_misc", "cached"):
        if label in counts:
            lines.append(f"{label:>32}:  {counts[label]}")
    lines.append("")

    if removed:
        lines.append("-" * 72)
        lines.append("Removed (unreferenced):")
        lines.append("-" * 72)
        for k in sorted(removed):
            lines.append(f"  - {k}")
        lines.append("")

    upgraded_keys = [k for k, r in results.items() if r["outcome"] == "upgraded"]
    if upgraded_keys:
        lines.append("-" * 72)
        lines.append("Upgraded to peer-reviewed venue:")
        lines.append("-" * 72)
        for k in sorted(upgraded_keys):
            r = results[k]
            new = rename_map.get(k, k)
            arrow = f"  {k}" if new == k else f"  {k} -> {new}"
            lines.append(f"{arrow}    [{r['reason']}]")
        lines.append("")

    normalized_keys = [k for k, r in results.items() if r["outcome"] == "normalized"]
    if normalized_keys:
        lines.append("-" * 72)
        lines.append("Normalized (refreshed entry, same category):")
        lines.append("-" * 72)
        for k in sorted(normalized_keys):
            lines.append(f"  - {k}    [{results[k]['reason']}]")
        lines.append("")

    stripped_entries = [(k, r["stripped_fields"]) for k, r in results.items()
                        if r["outcome"] == "stripped"]
    if stripped_entries:
        lines.append("-" * 72)
        lines.append("Stripped arXiv metadata from already-published entries:")
        lines.append("-" * 72)
        for k, fields in sorted(stripped_entries):
            lines.append(f"  - {k}    [stripped: {', '.join(fields)}]")
        lines.append("")

    no_match = [(k, r["reason"]) for k, r in results.items() if r["outcome"] == "no_match"]
    if no_match:
        lines.append("-" * 72)
        lines.append("No DBLP/Crossref match (review manually):")
        lines.append("-" * 72)
        for k, reason in sorted(no_match):
            lines.append(f"  - {k}    [{reason}]")
        lines.append("")

    if tex_counts:
        lines.append("-" * 72)
        lines.append("Cite-site rewrites in .tex files:")
        lines.append("-" * 72)
        for path, n in sorted(tex_counts.items()):
            lines.append(f"  {n:>4}  {path}")
        lines.append("")

    REPORT_FILE.write_text("\n".join(lines))
    print(f"Report written to {REPORT_FILE.name}")


def main():
    args = parse_args()
    only_keys = set(k.strip() for k in args.only.split(",") if k.strip())

    # Backup — only create if none exists so that a re-run never clobbers the
    # original. (Git history is the authoritative source; the backup is just
    # belt-and-braces for the first run before any external commit.)
    if not args.dry_run:
        if not BACKUP_FILE.exists():
            shutil.copy2(BIB_FILE, BACKUP_FILE)
            print(f"Backup: {BACKUP_FILE.name} (created)")
        else:
            print(f"Backup: {BACKUP_FILE.name} (kept existing — not overwritten)")

    # Parse bib
    parser = BibTexParser(common_strings=True)
    parser.ignore_nonstandard_types = False
    with open(BIB_FILE, encoding="utf-8") as f:
        bib_db = bibtexparser.load(f, parser=parser)
    print(f"Parsed {len(bib_db.entries)} entries")

    # Step 1: optional remove-unreferenced
    removed = []
    if args.remove_unref:
        print("\n--- Step 1: Remove unreferenced entries ---")
        referenced = keys_from_tex_files() | keys_from_aux()
        print(f"  Referenced (.tex ∪ .aux): {len(referenced)}")
        removed = remove_unreferenced(bib_db, referenced)
        print(f"  Removed: {len(removed)}")

    # Step 2/3/4: validate each entry
    print("\n--- Validate entries against DBLP / Crossref ---")
    cache = load_cache()
    results = {}        # citation_key -> result dict
    rename_map = {}     # old_key -> new_key
    new_cache = dict(cache)

    selectable = list(select_entries(bib_db, only_keys))
    if args.limit:
        selectable = selectable[:args.limit]
    total = len(selectable)
    processed = 0

    for n, (i, entry) in enumerate(selectable, 1):
        key = entry["ID"]
        chash = entry_hash(entry)

        if not args.force and is_fresh(cache.get(key), chash, args.max_age_days):
            results[key] = {"outcome": "cached", "reason": "cache fresh",
                            "new_entry": None, "new_key": None,
                            "stripped_fields": []}
            continue

        processed += 1
        print(f"  [{n}/{total}] {key[:55]:<55}", end=" ", flush=True)
        try:
            r = process_entry(entry, args)
        except Exception as e:
            print(f"ERROR: {e}")
            r = {"outcome": "no_match", "new_entry": None, "new_key": None,
                 "stripped_fields": [], "reason": f"exception: {e}"}
        results[key] = r

        # Apply changes to bib_db
        new_key_for_cache = key
        if r["outcome"] in ("upgraded", "normalized") and r["new_entry"] is not None:
            new_entry = r["new_entry"]
            new_id = new_entry["ID"]
            bib_db.entries[i] = new_entry
            label = r["outcome"].upper()
            if new_id != key:
                rename_map[key] = new_id
                new_key_for_cache = new_id
                print(f"{label} -> {new_id}")
            else:
                print(label)
        elif r["outcome"] == "stripped":
            print(f"STRIPPED ({', '.join(r['stripped_fields'])})")
        elif r["outcome"] == "no_match":
            print(f"NO MATCH ({r['reason']})")
        elif r["outcome"] == "skip_misc":
            print("SKIP (misc+url)")
        else:
            print("OK")

        # Update cache
        final_entry = bib_db.entries[i]
        new_cache[new_key_for_cache] = {
            "last_checked": now_iso(),
            "content_hash": entry_hash(final_entry),
            "outcome": r["outcome"],
            "arxiv_id": arxiv_id_from_entry(final_entry) or "",
        }
        if new_key_for_cache != key:
            new_cache.pop(key, None)

    print(f"\nProcessed {processed} of {total} (cached={total - processed})")

    # Dedupe: if multiple entries share an ID (typical when two source keys
    # got renamed to the same DBLP record), keep the first and report the rest.
    seen = {}
    duplicates = []
    deduped = []
    for e in bib_db.entries:
        if e["ID"] in seen:
            duplicates.append(e["ID"])
            continue
        seen[e["ID"]] = True
        deduped.append(e)
    if duplicates:
        bib_db.entries = deduped
        print(f"\nDeduplicated {len(duplicates)} entries collapsed by rename:")
        for k in duplicates:
            print(f"  - {k}")

    # Step 5: rewrite cite sites
    tex_counts = {}
    if rename_map and not args.no_tex_update:
        print(f"\n--- Rewriting cite sites in .tex files ({len(rename_map)} renamed keys) ---")
        tex_counts = rewrite_tex_citations(rename_map, dry_run=args.dry_run)
        for path, n in sorted(tex_counts.items()):
            print(f"  {n:>4}  {path}")
        if not tex_counts:
            print("  (no cite sites rewritten — keys may not be cited)")

    # Write bib
    if not args.dry_run:
        bib_db.entries.sort(key=lambda e: e["ID"].lower())
        writer = BibTexWriter()
        writer.indent = "  "
        writer.comma_first = False
        writer.order_entries_by = ("ID",)
        with open(BIB_FILE, "w", encoding="utf-8") as f:
            f.write(writer.write(bib_db))
        print(f"\nWrote {len(bib_db.entries)} entries to {BIB_FILE.name}")
        save_cache(new_cache)
        print(f"Cache: {CACHE_FILE.relative_to(PROJECT)}")
    else:
        print("\n[dry-run] no files written")

    write_report(removed, results, rename_map, tex_counts)


if __name__ == "__main__":
    main()
